export const SET_USER_TYPE = "SET_USER_TYPE";

export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const VERIFY_OTP_USER_REQUESTED = "VERIFY_OTP_USER_REQUESTED"
export const VERIFY_OTP_USER_SUCCESS = "VERIFY_OTP_USER_SUCCESS"
export const VERIFY_OTP_USER_FAILURE = "VERIFY_OTP_USER_FAILURE"

export const USER_LOGOUT = "USER_LOGOUT"
