export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_REQUEST_SUCCESS = "ADD_POST_REQUEST_SUCCESS";
export const ADD_POST_REQUEST_FAILED = "ADD_POST_REQUEST_FAILED";

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST_REQUEST_SUCCESS =
  "GET_SINGLE_POST_REQUEST_SUCCESS";
export const GET_SINGLE_POST_REQUEST_FAILED = "GET_SINGLE_POST_REQUEST_FAILED";

export const UPDATE_SINGLE_POST_REQUEST = "UPDATE_SINGLE_POST_REQUEST";
export const UPDATE_SINGLE_POST_REQUEST_SUCCESS =
  "UPDATE_SINGLE_POST_REQUEST_SUCCESS";
export const UPDATE_SINGLE_POST_REQUEST_FAILED =
  "UPDATE_SINGLE_POST_REQUEST_FAILED";

export const GET_GROUP_SINGLE_POST_REQUEST = "GET_GROUP_SINGLE_POST_REQUEST";
export const GET_GROUP_SINGLE_POST_REQUEST_SUCCESS =
  "GET_GROUP_SINGLE_POST_REQUEST_SUCCESS";
export const GET_GROUP_SINGLE_POST_REQUEST_FAILED =
  "GET_GROUP_SINGLE_POST_REQUEST_FAILED";

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_REQUEST_SUCCESS = "GET_ALL_POSTS_REQUEST_SUCCESS";
export const GET_ALL_POSTS_REQUEST_FAILED = "GET_ALL_POSTS_REQUEST_FAILED";

export const VOTE_SINGLE_POST_REQUEST = "VOTE_SINGLE_POST_REQUEST";
export const VOTE_SINGLE_POST_REQUEST_SUCCESS =
  "VOTE_SINGLE_POST_REQUEST_SUCCESS";
export const VOTE_SINGLE_POST_REQUEST_FAILED = "VOTE_SINGLE_POST_REQUEST_FAILED";

export const UPDATE_COMPLAIN_REQUEST = "UPDATE_COMPLAIN_REQUEST";
export const UPDATE_COMPLAIN_REQUEST_SUCCESS =
  "UPDATE_COMPLAIN_REQUEST_SUCCESS";
export const UPDATE_COMPLAIN_REQUEST_FAILED = "UPDATE_COMPLAIN_REQUEST_FAILED";