export const GET_LOGGED_USER_REQUEST = "GET_LOGGED_USER_REQUEST";
export const GET_LOGGED_USER_RECEIVED = "GET_LOGGED_USER_RECEIVED";
export const GET_LOGGED_USER_FAILED = "GET_LOGGED_USER_FAILED";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_RECEIVED = "CHANGE_PASSWORD_RECEIVED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";


export const CHANGE_USER_DATA_REQUEST = "CHANGE_USER_DATA_REQUEST";
export const CHANGE_USER_DATA_RECEIVED = "CHANGE_USER_DATA_RECEIVED";
export const CHANGE_USER_DATA_FAILED = "CHANGE_USER_DATA_FAILED";