export const GET_ALL_INSTRUCTORS_REQUEST = "GET_ALL_INSTRUCTORS_REQUEST";
export const GET_ALL_INSTRUCTORS_RECEIVED = "GET_ALL_INSTRUCTORS_RECEIVED";
export const GET_ALL_INSTRUCTORS_FAILED = "GET_ALL_INSTRUCTORS_FAILED";

export const GET_ALL_TA_REQUEST = "GET_ALL_TA_REQUEST";
export const GET_ALL_TA_RECEIVED = "GET_ALL_TA_RECEIVED";
export const GET_ALL_TA_FAILED = "GET_ALL_TA_FAILED";

export const GET_LOGGED_USER_REQUEST = "GET_LOGGED_USER_REQUEST";
export const GET_LOGGED_USER_RECEIVED = "GET_LOGGED_USER_RECEIVED";
export const GET_LOGGED_USER_FAILED = "GET_LOGGED_USER_FAILED";


export const GET_LOGGED_USER_ENROLLED_COURSE_REQUEST = "GET_LOGGED_USER_ENROLLED_COURSE_REQUEST";
export const GET_LOGGED_USER_ENROLLED_COURSE_RECEIVED = "GET_LOGGED_USER_ENROLLED_COURSE_RECEIVED";
export const GET_LOGGED_USER_ENROLLED_COURSE_FAILED = "GET_LOGGED_USER_ENROLLED_COURSE_FAILED";

export const GET_LIKE_COURSES_REQUEST = "GET_LIKE_COURSES_REQUEST";
export const GET_LIKE_COURSES_RECEIVED = "GET_LIKE_COURSES_RECEIVED";
export const GET_LIKE_COURSES_FAILED = "GET_LIKE_COURSES_FAILED";


export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_RECEIVED = "CHANGE_PASSWORD_RECEIVED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";


export const CHANGE_USER_DATA_REQUEST = "CHANGE_USER_DATA_REQUEST";
export const CHANGE_USER_DATA_RECEIVED = "CHANGE_USER_DATA_RECEIVED";
export const CHANGE_USER_DATA_FAILED = "CHANGE_USER_DATA_FAILED";